services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: dbgate
    ports:
      - "${CLIENT_PORT}:3000"     
    env_file:
      - .env
    volumes:
      - client_data:/root/.dbgate
    networks:
      - um-base-de-datos-sqlserver

  mssql:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: mssql
    ports:
      - "${SQLSERVER_PORT}:1433"
    env_file:
      - .env
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - um-base-de-datos-sqlserver

  cli-tool:
    build:
      context: .
      dockerfile: Dockerfile.cli-tool
    container_name: cli-tool
    env_file:
      - .env
    command: sleep infinity
    stdin_open: true
    tty: true
    networks:
      - um-base-de-datos-sqlserver

networks:
  um-base-de-datos-sqlserver:
    driver: bridge

volumes:
  client_data:
  mssql_data: