version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: dbgate
    ports:
      - "${CLIENT_PORT}:3000"     
    env_file:
      - .env
    volumes:
      - ./volumes/client:/root/.dbgate
    networks:
      - um-base-de-datos-sqlserver

  mssql:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: mssql
    ports:
      - "${SQLSERVER_PORT}:1433"
    env_file:
      - .env
    volumes:
      - ./volumes/mssql:/var/opt/mssql
    networks:
      - um-base-de-datos-sqlserver

networks:
  um-base-de-datos-sqlserver:
    driver: bridge